package bp.assignment.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-12T19:32:30.869+01:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://services.assignment.bp/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @RequestWrapper(localName = "addUser", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.AddUser")
    @WebMethod
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.AddUserResponse")
    public void addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUsers", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.FindUsers")
    @WebMethod
    @ResponseWrapper(localName = "findUsersResponse", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.FindUsersResponse")
    public java.util.List<java.lang.String> findUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findOldestUser", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.FindOldestUser")
    @WebMethod
    @ResponseWrapper(localName = "findOldestUserResponse", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.FindOldestUserResponse")
    public java.lang.String findOldestUser();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "averageAge", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.AverageAge")
    @WebMethod
    @ResponseWrapper(localName = "averageAgeResponse", targetNamespace = "http://services.assignment.bp/", className = "bp.assignment.services.AverageAgeResponse")
    public int averageAge();
}
